general:
    start_dir: .
    enable_logging: true
player:
    shuffle: true
    repeat_playlist: true
music:
    repeat_song: false
    repeat_playlist: true
    shuffle: true
renderer: raw
user:
    use_db: false
temp:
    start_dir: ""
    show_icons: false
    show_hidden: false
    exclude: []
    playonly: []
    include: []
    renderer: ""
    enable_logging: false
